---
title: "HPMC Hand Hygiene Report"
date: '`r Sys.Date()`'
output: 
  html_document: 
    toc: yes
editor_options: 
  chunk_output_type: console
---

```{css, echo = F}

.main-container {
    max-width: 1920px;
    margin-left: auto;
    margin-right: auto;
}

```


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)

library(tidyverse)
library(googlesheets4)
library(lubridate)
library(broom)
library(gt)
library(reactable)

data <- local({

  gs4_deauth()

  df <- read_sheet('1EhL70rRwvAjBUcLuqI1PPxcNk4h_LAzaxWqJm5m6x4w')

  df <- df %>% janitor::clean_names()

  df <- df %>%
    mutate(
      timestamp = date(timestamp)
    )

  df <- df %>%
    mutate(
      across(where(is.character), ~ ifelse(.x == 'N/A', NA, .x))
    )

  df <- df %>%
    mutate(
      compliant = case_when(
        hand_hygiene_compliance %in% c('Wash', 'Rub') ~ 1,
        TRUE ~ 0
      )
    )

  df <- df %>%
    mutate(
      timestamp = mdy(paste0(month(timestamp), '-1-', year(timestamp)))
    )

  df

})

# write_csv(data, 'data/processed_handhygiene_data.csv')

# data <- read_csv('data/processed_handhygiene_data.csv')

```

# Figure - Hand Hygiene Compliance
```{r}

out <- local({
  
  plot_data <- data %>%
    group_by('year' = year(timestamp), 'month' = month(timestamp, label = T)) %>%
    summarise(
      total_audits = n(),
      compliant_hh = sum(compliant == 1),
      non_compliant_hh = sum(compliant == 0),
      .groups = 'drop'
    ) %>%
    rowwise() %>%
    mutate(
      res = list(prop.test(compliant_hh, total_audits) %>% tidy())
    ) %>%
    unnest(res) %>%
    select(
      year, month, total_audits, compliant_hh, non_compliant_hh, estimate, conf.low, conf.high
    ) %>%
    mutate(
      timestamp = mdy(paste0(month, '-1-', year))
    ) %>%
    relocate(timestamp)
  
  year_xintercepts <- plot_data %>%
    group_by(year) %>%
    slice_min(timestamp) %>%
    pull(timestamp)
  
  plot <- ggplot(plot_data, aes(x = timestamp, y = estimate)) + 
    geom_point() + 
    geom_line() +
    geom_vline(xintercept = year_xintercepts, linetype = 'dashed', alpha = .5) +
    geom_ribbon(aes(ymin = conf.low, ymax = conf.high), alpha = .25) +
    labs(x = NULL, y = 'Percent Compliance (%)', caption = 'Ribbon depicts 95% CI of Percent Compliance') +
    scale_y_continuous(labels = scales::percent_format(), limits = c(0, 1)) +
    scale_x_date(breaks = year_xintercepts, date_labels = '%Y') +
    theme_light() + 
    theme(panel.grid.minor = element_blank(),
          axis.title = element_text(face = 'bold'))
  
  plot
  
  table <- plot_data %>% 
    select(-timestamp) %>%
    mutate(across(c(estimate, conf.low, conf.high), ~ scales::percent(.x, .1))) %>%
    group_nest(year) %>%
    arrange(year)
  
  table <- set_names(table$data, table$year)
  
  tibble::lst(table, plot)
})

```

```{r, out.width='75%', fig.height=5, fig.width=10, fig.align='center'}
out$plot
```

# Table - Hand Hygiene Compliance {.tabset}
```{r, results = 'asis'}

iwalk(rev(out$table), ~ {
  
  cat('## ', .y, '\n\n')

  .x %>%
    gt() %>%
    cols_label(
      month = 'Month',
      total_audits = 'Total Audits',
      compliant_hh = 'Compliant Audits',
      non_compliant_hh = 'Non Compliant Audits',
      estimate = 'Percent Compliant',
      conf.low = 'Lower CI',
      conf.high = 'Upper CI'
    ) %>%
    print()
  
  cat('\n\n')
  
})

```

# Table - Hand Hygiene Compliance by Opportunity {.tabset}
```{r, results='asis'}

out <- local({
  res <- data %>%
    group_by(
      'year' = year(timestamp),
      'month' = month(timestamp, label = T),
      opportunity
    ) %>%
    summarise(
      total_audits = n(),
      compliant_hh = sum(compliant == 1),
      non_compliant_hh = sum(compliant == 0),
      .groups = 'drop'
    ) %>%
    rowwise() %>%
    mutate(res = list(prop.test(compliant_hh, total_audits) %>% tidy())) %>%
    unnest(res) %>%
    mutate(across(c(estimate, conf.low, conf.high), ~ scales::percent(.x, .1))) %>%
    select(
      year,
      month,
      opportunity,
      total_audits,
      compliant_hh,
      non_compliant_hh,
      estimate,
      conf.low,
      conf.high
    ) %>%
    group_nest(year, month) %>%
    arrange(desc(year), desc(month))
  
  
})

walk(unique(out$year), function(i) {
  cat('## ', i, '{.tabset}\n\n')
  
  walk(as.character(out[out$year == i, ]$month), function(j) {
    cat('### ', j, '\n\n')
    
    out[out$year == i & out$month == j, ]$data[[1]] %>%
      gt() %>%
      cols_label(
        opportunity = 'Opportunity',
        total_audits = 'Total Audits',
        compliant_hh = 'Compliant Audits',
        non_compliant_hh = 'Non Compliant Audits',
        estimate = 'Percent Compliant',
        conf.low = 'Lower CI',
        conf.high = 'Upper CI'
      ) %>%
      print()
    
    cat('\n\n')
    
  })
  
})

```

# Table - Hand Hygiene Compliance by Discipline {.tabset}
```{r, results = 'asis'}

out <- local({
  res <- data %>%
    group_by('year' = year(timestamp),
             'month' = month(timestamp, label = T),
             hcw) %>%
    summarise(
      total_audits = n(),
      compliant_hh = sum(compliant == 1),
      non_compliant_hh = sum(compliant == 0),
      .groups = 'drop'
    ) %>%
    rowwise() %>%
    mutate(res = list(prop.test(compliant_hh, total_audits) %>% tidy())) %>%
    unnest(res) %>%
    mutate(across(c(estimate, conf.low, conf.high), ~ scales::percent(.x, .1))) %>%
    select(
      year,
      month,
      hcw,
      total_audits,
      compliant_hh,
      non_compliant_hh,
      estimate,
      conf.low,
      conf.high
    ) %>%
    group_nest(year, month) %>%
    arrange(desc(year), desc(month))
  
  res
  
  
})

walk(unique(out$year), function(i) {
  cat('## ', i, '{.tabset}\n\n')
  
  walk(as.character(out[out$year == i, ]$month), function(j) {
    cat('### ', j, '\n\n')
    
    out[out$year == i & out$month == j, ]$data[[1]] %>%
      gt() %>%
      cols_label(
        hcw = 'Discipline',
        total_audits = 'Total Audits',
        compliant_hh = 'Compliant Audits',
        non_compliant_hh = 'Non Compliant Audits',
        estimate = 'Percent Compliant',
        conf.low = 'Lower CI',
        conf.high = 'Upper CI'
      ) %>%
      print()
    
    cat('\n\n')
    
  })
  
})

```
























